[build]
command = "npm run build"
publish = "dist"

[build.processing]
skip_processing = true

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
